#include "crane.h"
#include <iostream>
#include <algorithm>

int main(){
	//Pájnusz monochrome perpetuity
	Crane c("hcedffhcjjhgbgjiiadgecifjedjfffgedcbgaiijdciffgjaeihcdbgffagdjabcjecgbajdibjgdfbefdcadcjcjgdgbcdfeeacffidiijajgcafbijiaeifdcafjahhgffbhdajdccbadaejeehjdgaadefejhdijgdacbfjbgedeccjibhfiaaaibgffghhcfedigbcidigcaeigjgabgbdhiedghjjgfbeeajjgcihebfjaheajaddjacgbdgbdbdcjbbbjdhebaeheadaedcjcgehcjeeagcgbehhjicfbcjadfjefgeehdbdbdeggdaaifihagihhbdeehbeddbfdaabgfiefjjecaabgdebheadfchidaahieahjahaeidffcgcbachhighggifccidadfhhghhfjidageeigidajeggdhaacajiebjdchejdbfbicihbjgbchjabdeedfhceeaafccdjfjfgjdafddgaajeihfjbbfgcehfjhibjdfgcfgghijahfhbjjigacdgiebdeadbfjjjhgeabgaahjffchcjjaghaeedefdadijbaabadhdadhfeidbbgeiaiigijagabbjcgegcbcebaaiafhggajcfageeddiiaeahbaaijgdfcjggbbccghbbdhhfcfdhdjeifgjdjjjibfjgcjgdaibfejiibifcebijadebeefibajcbiibafejiacdefacdchidhfgjdhicdbedfjgfdaijfadhcdbjhaibjidgfigahggfcbjieeficjheeccgjfcgbihgbhjghjfgiccibbgghgigfegehjeiaiicjgdaeedhjibfiddcbfjdaghbaddbffeidghfiehfjjgdjjcjgadjgbjdeejbeagidjhgfeciedcddjafcejhdcbccejffcchhibceaijhcdhbciaehgagjgeidecjgffhbfijfeegheccajbdaajdddfgad",
			"hcedffggjfbabjhaiabbijhhebgcgaeejchegjchjabcegdaiijgbgdiigdcacaihagihibjdfghbghibgcfjgcchaeidfeehjdgaiaaaijifchdajdghhacfddjfjgjcdfeieajhadfigjaajfgicfgdcchfiehfgigjbigjgagjiafhbjjjhfgbdcejbfacgeegaaajeibdbdihdebgaijefabiibcjcjcdacdfdhjefedaijddjaajdbajidajciiaajgfaabgciiijbdjfeeedeccjgaacbbggjfcjcibbggcjebaaiahdhacbgideifecfibibgffghhheijjhgeabfjbehbjgdifbcacfdhdjeifecffeidgfaaeegfhdheegeeibceaijhcdfaeheahfdbcddaffbijagabbigccajbdhbjgdfbjebdehjcifeebhecdeebgeiaigebdjcadhdahgfebjjgfajdecjchiabiciidiifbhcecidadfheihdbgihajaddjacgfhggajcfagejfejdbfgdjabcjecgbjibgbdbdbfhhdeggdaajjchcffiejfaecjdaeedhgegcjdaiaffhbifffgjjjhccffjeacbgdfedagjgieacfhaeebeiefedddcdcjjdgjeicgcbaheajdedabdffhdgggjdhgdabigadjccbcdhjjajhjafdeedgadhgaaeihjfhecjdeagifgdijbdhdbjgdgchhiedcbgachdfchidaahajhddiahbfijefbdghbgbhgjcfiajcfdiiccajdfadhcicdbedfjafcejfbdaebbbjbefgeedhebjhjhgfeciefjaeibehicgjjaeebdghjdcbcdfgbbhgifjdjgfdajfaccjghabcgdaibhbdebfgbchbaddbdgddgaffieaicbhifjhggiijdcifcejjfeafegefgighddegghijaheigdfjicf");
	//std::cout << c.stringflip("aaabbbccc", 1, 3) << std::endl;
	c.sort();
	c.getresults();
	/*std::string valami("abcdefgh");
	std::cout << std::endl << std::string(valami.rbegin(), valami.rend()) << std::endl;
	std::cout << valami.substr(2, 4) << std::endl;
	std::cout << c.stringflip(valami, 2, 6);
	getchar();*/
	/*std::string fasztalicskakettõ = "abcthzhjuk";
	std::sort(fasztalicskakettõ.begin(), fasztalicskakettõ.begin() + 6);
	std::cout << fasztalicskakettõ;*/
	//while (true){}
}